[2022-10-11 10:10:53,687] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: weekly_batch.GCStoBQ_task manual__2022-10-11T10:10:36.535603+00:00 [queued]>
[2022-10-11 10:10:53,699] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: weekly_batch.GCStoBQ_task manual__2022-10-11T10:10:36.535603+00:00 [queued]>
[2022-10-11 10:10:53,700] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-10-11 10:10:53,700] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-10-11 10:10:53,701] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-10-11 10:10:53,714] {taskinstance.py:1259} INFO - Executing <Task(GCSToBigQueryOperator): GCStoBQ_task> on 2022-10-11 10:10:36.535603+00:00
[2022-10-11 10:10:53,720] {standard_task_runner.py:52} INFO - Started process 233 to run task
[2022-10-11 10:10:53,723] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'weekly_batch', 'GCStoBQ_task', 'manual__2022-10-11T10:10:36.535603+00:00', '--job-id', '117', '--raw', '--subdir', 'DAGS_FOLDER/bank_weekly_ingest_dag.py', '--cfg-path', '/tmp/tmpfu3_0rxp', '--error-file', '/tmp/tmpkmq6yvct']
[2022-10-11 10:10:53,724] {standard_task_runner.py:77} INFO - Job 117: Subtask GCStoBQ_task
[2022-10-11 10:10:53,774] {logging_mixin.py:109} INFO - Running <TaskInstance: weekly_batch.GCStoBQ_task manual__2022-10-11T10:10:36.535603+00:00 [running]> on host 57053c33f100
[2022-10-11 10:10:53,855] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weekly_batch
AIRFLOW_CTX_TASK_ID=GCStoBQ_task
AIRFLOW_CTX_EXECUTION_DATE=2022-10-11T10:10:36.535603+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-11T10:10:36.535603+00:00
[2022-10-11 10:10:53,874] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/providers/google/cloud/transfers/gcs_to_bigquery.py:261: DeprecationWarning: The bigquery_conn_id parameter has been deprecated. You should pass the gcp_conn_id parameter.
  impersonation_chain=self.impersonation_chain,

[2022-10-11 10:10:53,882] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-10-11 10:10:53,890] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/providers/google/cloud/hooks/bigquery.py:141: DeprecationWarning: This method will be deprecated. Please use `BigQueryHook.get_client` method
  "This method will be deprecated. Please use `BigQueryHook.get_client` method", DeprecationWarning

[2022-10-11 10:10:55,309] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py:1511: DeprecationWarning: This method is deprecated. Please use `***.providers.google.cloud.hooks.bigquery.BigQueryHook.run_load`
  result = execute_callable(context=context)

[2022-10-11 10:10:55,311] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/providers/google/cloud/hooks/bigquery.py:1772: DeprecationWarning: This method is deprecated. Please use `BigQueryHook.insert_job` method.
  "This method is deprecated. Please use `BigQueryHook.insert_job` method.", DeprecationWarning

[2022-10-11 10:10:55,314] {bigquery.py:1637} INFO - Inserting job ***_1665483055313481_646074561a5dc86cfada964546f0c848
[2022-10-11 10:10:56,891] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 329, in execute
    description=self.description,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 2682, in run_load
    return self.hook.run_load(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1917, in run_load
    job = self.insert_job(configuration=configuration, project_id=self.project_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: URI gs://wfwijaya-fellowship/data-lake/bank-additional-full.csv
[2022-10-11 10:10:56,908] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=weekly_batch, task_id=GCStoBQ_task, execution_date=20221011T101036, start_date=20221011T101053, end_date=20221011T101056
[2022-10-11 10:10:56,932] {standard_task_runner.py:92} ERROR - Failed to execute job 117 for task GCStoBQ_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 329, in execute
    description=self.description,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 2682, in run_load
    return self.hook.run_load(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1917, in run_load
    job = self.insert_job(configuration=configuration, project_id=self.project_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: URI gs://wfwijaya-fellowship/data-lake/bank-additional-full.csv
[2022-10-11 10:10:56,951] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-10-11 10:10:56,985] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
